stages:
  - prepare
  - build
  - test
  - deploy

## defaults:
variables:
  #TARGET: "armv7hl"
  TARGET: "i486" # is fastest

.build-local:
  image:
      #name: "sailfishos-platform-sdk:3.3_3.4"
      name: "coderus/sailfishos-platform-sdk-$TARGET:$SFOS_VERSION"
      entrypoint: [""]
  timeout: 1h 30m
  tags:
    - docker
  cache:
    tag: ${CI_PROJECT_NAME}_${CI_JOB_NAME}
    key: ${CI_PROJECT_NAME}_${CI_COMMIT_REF_SLUG}
    paths:
      - "/cache/zypp"
      - "$CI_PROJECT_DIR/myrepo"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    SFOS_VERSION: 3.4.0.24
    TARGET: armv7hl
    SPECNAME: openrepos-cool-retro-term.spec
    YAMLNAME: openrepos-cool-retro-term.yaml
  before_script:
    - mkdir -p $CI_PROJECT_DIR/qmltermwidget/rpm/
    - cp $CI_PROJECT_DIR/rpm/qmltermwidget.spec $CI_PROJECT_DIR/qmltermwidget/rpm/
  script:
    - OUTDIR=$CI_PROJECT_DIR/output
    - BLDDIR=~/build
    - mkdir -p ${OUTDIR}
    # mkdir -p ${BLDDIR}
    - cp -r $CI_PROJECT_DIR ${BLDDIR}
    - pushd ${BLDDIR}
    - rm -rf RPMS/*
    - pwd
    - ls -l
    # mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./qmltermwidget/rpm/qmltermwidget.spec --no-fix-version prepare --enable-debug $BLDDIR | tee $OUTDIR/prepare.log
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./rpm/$SPECNAME --no-fix-version prepare --enable-debug $BLDDIR | tee $OUTDIR/prepare.log
    # cp -r files/* qml/* rpm/
    # mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./qmltermwidget/rpm/qmltermwidget.spec --no-fix-version build   --enable-debug $BLDDIR | tee $OUTDIR/build.log
    - mb2 -t SailfishOS-$SFOS_VERSION-$TARGET --specfile ./rpm/$SPECNAME --no-fix-version build   --enable-debug $BLDDIR | tee $OUTDIR/build.log
    - pwd
    - ls -l
    - ls -l $CI_PROJECT_DIR
    - mkdir -p $OUTDIR/$SFOS_VERSION
    - cp -r RPMS/* ${OUTDIR}/$SFOS_VERSION
    - cp -r qml/*ts ${OUTDIR}/
    - cp -r rpm/* ${OUTDIR}


